# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 17:06
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted', models.BooleanField(default=False, verbose_name='eliminado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='Santa Marta, Magdalena', max_length=255, verbose_name='Ciudad')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario acual')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
